-- Seeds franchise_rules, publisher_tiers, and genres with the real curation data that was ported in
-- code (franchise_assigner.py, publisher_tier.py, genre_service.py) from the legacy standalone
-- Tools/PlayStation/*.py scripts, but never actually migrated into these tables as rows. Until this
-- migration, all three tables were empty, so franchise/tier/genre resolution silently produced
-- nothing (franchise="" for every game, aaa_tier="Indie" for every enriched game, genre="" whenever
-- reconcile_genres had no priority to rank against) -- the Catalog page's Franchise/Genre/Tier
-- filters returned zero results for any value as a result.

-- franchise_rules: ported from Tools/PlayStation/ps_curate.py's FRANCHISE_MAP list. priority is the
-- list's original index -- assign_franchise() sorts ascending by priority and takes the first match,
-- so preserving the list's order preserves its existing first-match-wins semantics exactly.
INSERT INTO franchise_rules (pattern, franchise, priority)
VALUES ('assassin.s creed', 'Assassin''s Creed', 0),
       ('call of duty', 'Call of Duty', 1),
       ('resident evil', 'Resident Evil', 2),
       ('final fantasy (xv|vii|viii|ix|x|xi|xii|xiii|xiv|xvi|vii remake|vii rebirth)', 'Final Fantasy', 3),
       ('final fantasy', 'Final Fantasy', 4),
       ('crisis core.{0,5}final fantasy', 'Final Fantasy', 5),
       ('yakuza|like a dragon|judgment|lost judgment|ishin', 'Like a Dragon / Yakuza', 6),
       ('lego\b', 'LEGO', 7),
       ('\bfar cry\b', 'Far Cry', 8),
       ('need for speed', 'Need for Speed', 9),
       ('\bpersona [3-6]\b', 'Persona', 10),
       ('uncharted', 'Uncharted', 11),
       ('god of war', 'God of War', 12),
       ('spider.man', 'Spider-Man', 13),
       ('batman.{0,10}arkham', 'Batman: Arkham', 14),
       ('watch.?dogs', 'Watch Dogs', 15),
       ('ghost of tsushima', 'Ghost of Tsushima', 16),
       ('the witcher', 'The Witcher', 17),
       ('horizon (zero|forbidden|call)', 'Horizon', 18),
       ('borderlands', 'Borderlands', 19),
       ('\bdestiny\b', 'Destiny', 20),
       ('\bfifa\b|ea sports fc|\beas fc\b', 'FIFA / EA Sports FC', 21),
       ('\bnba 2k', 'NBA 2K', 22),
       ('\bmlb the show\b', 'MLB The Show', 23),
       ('\bfallout\b', 'Fallout', 24),
       ('elder scrolls', 'The Elder Scrolls', 25),
       ('\b(elden ring|dark souls|demon.s souls|sekiro|bloodborne)\b', 'FromSoftware', 26),
       ('crash bandicoot', 'Crash Bandicoot', 27),
       ('ratchet.{0,5}clank', 'Ratchet & Clank', 28),
       ('\bsackboy\b', 'Sackboy', 29),
       ('coffee talk', 'Coffee Talk', 30),
       ('jackbox', 'Jackbox Party Pack', 31),
       ('\bovercooked\b', 'Overcooked', 32),
       ('little nightmares', 'Little Nightmares', 33),
       ('mafia (i|ii|iii|definitive|trilogy)', 'Mafia', 34),
       ('\bgta |grand theft auto', 'Grand Theft Auto', 35),
       ('red dead', 'Red Dead', 36),
       ('dragon age', 'Dragon Age', 37),
       ('mass effect', 'Mass Effect', 38),
       ('mortal kombat', 'Mortal Kombat', 39),
       ('street fighter', 'Street Fighter', 40),
       ('\btekken\b', 'Tekken', 41),
       ('tales of\b', 'Tales Of', 42),
       ('atelier\b', 'Atelier', 43),
       ('persona\b', 'Persona', 44),
       ('dragon quest', 'Dragon Quest', 45),
       ('\bnioh\b', 'Nioh', 46),
       ('metro (exodus|2033|last light)', 'Metro', 47),
       ('wolfenstein', 'Wolfenstein', 48),
       ('\bdoom\b', 'DOOM', 49),
       ('alan wake', 'Alan Wake', 50),
       ('the quarry|man of medan|little hope|house of ashes|the devil in me|the outlast|outlast', 'Horror', 51),
       ('a plague tale', 'A Plague Tale', 52),
       ('star wars jedi', 'Star Wars Jedi', 53),
       ('monster hunter', 'Monster Hunter', 54),
       ('devil may cry', 'Devil May Cry', 55),
       ('diablo\b', 'Diablo', 56),
       ('overwatch\b', 'Overwatch', 57),
       ('sims?\b', 'The Sims', 58),
       ('nfs|need for speed', 'Need for Speed', 59),
       ('\banno \d{4}\b', 'Anno', 60),
       ('\bark: survival', 'ARK', 61),
       ('\bbattlefield\b', 'Battlefield', 62),
       ('darksiders', 'Darksiders', 63),
       ('dishonored', 'Dishonored', 64),
       ('earth defense force', 'Earth Defense Force', 65),
       ('five nights at freddy', 'Five Nights at Freddy''s', 66),
       ('ghostrunner', 'Ghostrunner', 67),
       ('goat simulator', 'Goat Simulator', 68),
       ('granblue fantasy', 'Granblue Fantasy', 69),
       ('hello neighbor', 'Hello Neighbor', 70),
       ('\bhitman\b', 'Hitman', 71),
       ('hot wheels', 'Hot Wheels', 72),
       ('just cause', 'Just Cause', 73),
       ('killing floor', 'Killing Floor', 74),
       ('life is strange', 'Life is Strange', 75),
       ('sniper elite', 'Sniper Elite', 76),
       ('\bsonic\b', 'Sonic', 77),
       ('south park', 'South Park', 78),
       ('tom clancy', 'Tom Clancy', 79),
       ('tomb raider', 'Tomb Raider', 80),
       ('\btrials\b', 'Trials', 81),
       ('\btropico\b', 'Tropico', 82),
       ('two point\b', 'Two Point', 83),
       ('warhammer', 'Warhammer', 84),
       ('\bys [ivx]', 'Ys', 85);

-- publisher_tiers: ported from Tools/PlayStation/ps_enrich.py's AAA_PUBLISHERS/AA_PUBLISHERS sets.
-- match_kind='substring' reproduces classify_tier()'s `pattern in lower` check, matching the legacy
-- sets' `any(p in pub_lower for p in ...)` behavior exactly.
INSERT INTO publisher_tiers (pattern, tier, match_kind)
VALUES ('sony interactive entertainment', 'AAA', 'substring'),
       ('playstation studios', 'AAA', 'substring'),
       ('electronic arts', 'AAA', 'substring'),
       ('ea sports', 'AAA', 'substring'),
       ('ubisoft', 'AAA', 'substring'),
       ('rockstar games', 'AAA', 'substring'),
       ('take-two interactive', 'AAA', 'substring'),
       ('activision', 'AAA', 'substring'),
       ('activision blizzard', 'AAA', 'substring'),
       ('2k games', 'AAA', 'substring'),
       ('2k sports', 'AAA', 'substring'),
       ('bethesda softworks', 'AAA', 'substring'),
       ('bethesda', 'AAA', 'substring'),
       ('square enix', 'AAA', 'substring'),
       ('capcom', 'AAA', 'substring'),
       ('konami', 'AAA', 'substring'),
       ('bandai namco entertainment', 'AAA', 'substring'),
       ('bandai namco', 'AAA', 'substring'),
       ('warner bros. games', 'AAA', 'substring'),
       ('warner bros', 'AAA', 'substring'),
       ('wb games', 'AAA', 'substring'),
       ('microsoft game studios', 'AAA', 'substring'),
       ('xbox game studios', 'AAA', 'substring'),
       ('naughty dog', 'AAA', 'substring'),
       ('insomniac games', 'AAA', 'substring'),
       ('guerrilla games', 'AAA', 'substring'),
       ('santa monica studio', 'AAA', 'substring'),
       ('sucker punch productions', 'AAA', 'substring'),
       ('cd projekt', 'AAA', 'substring'),
       ('cd projekt red', 'AAA', 'substring'),
       ('from software', 'AAA', 'substring'),
       ('fromsoftware', 'AAA', 'substring'),
       ('atlus', 'AAA', 'substring'),
       ('sega', 'AAA', 'substring'),
       ('namco', 'AAA', 'substring'),
       ('disney interactive', 'AAA', 'substring'),
       ('lucasfilm games', 'AAA', 'substring'),
       ('eidos interactive', 'AAA', 'substring'),
       ('crystal dynamics', 'AAA', 'substring'),
       ('io interactive', 'AAA', 'substring'),
       ('epic games', 'AAA', 'substring'),
       ('riot games', 'AAA', 'substring'),
       ('bungie', 'AAA', 'substring'),
       ('infinity ward', 'AAA', 'substring'),
       ('treyarch', 'AAA', 'substring'),
       ('sledgehammer games', 'AAA', 'substring'),
       ('respawn entertainment', 'AAA', 'substring'),
       ('bioware', 'AAA', 'substring'),
       ('obsidian entertainment', 'AAA', 'substring'),
       ('focus entertainment', 'AA', 'substring'),
       ('focus home interactive', 'AA', 'substring'),
       ('thq nordic', 'AA', 'substring'),
       ('505 games', 'AA', 'substring'),
       ('team17', 'AA', 'substring'),
       ('paradox interactive', 'AA', 'substring'),
       ('plaion', 'AA', 'substring'),
       ('deep silver', 'AA', 'substring'),
       ('nacon', 'AA', 'substring'),
       ('microids', 'AA', 'substring'),
       ('maximum games', 'AA', 'substring'),
       ('koei tecmo', 'AA', 'substring'),
       ('nippon ichi software', 'AA', 'substring'),
       ('nis america', 'AA', 'substring'),
       ('arc system works', 'AA', 'substring'),
       ('spike chunsoft', 'AA', 'substring'),
       ('idea factory', 'AA', 'substring'),
       ('aksys games', 'AA', 'substring'),
       ('xseed games', 'AA', 'substring'),
       ('marvelous', 'AA', 'substring'),
       ('grasshopper manufacture', 'AA', 'substring'),
       ('tango gameworks', 'AA', 'substring'),
       ('crafts & meister', 'AA', 'substring'),
       ('wired productions', 'AA', 'substring'),
       ('raw fury', 'AA', 'substring'),
       ('devolver digital', 'AA', 'substring'),
       ('annapurna interactive', 'AA', 'substring'),
       ('private division', 'AA', 'substring'),
       ('curve games', 'AA', 'substring'),
       ('curve digital', 'AA', 'substring');

-- genres: ported from Tools/PlayStation/ps_genre.py's GENRE_PRIORITY list. priority is the list's
-- original ascending index -- pick_genre_subgenre() ranks lower priority as more specific/preferred,
-- matching the legacy list's existing "most specific/descriptive first" order.
INSERT INTO genres (name, priority, active)
VALUES ('Shooter', 0, true),
       ('Fighting', 1, true),
       ('RPG', 2, true),
       ('MOBA', 3, true),
       ('Sport', 4, true),
       ('Sports', 5, true),
       ('Driving/Racing', 6, true),
       ('Racing', 7, true),
       ('Platformer', 8, true),
       ('Puzzle', 9, true),
       ('Rhythm', 10, true),
       ('Horror', 11, true),
       ('Strategy', 12, true),
       ('Adventure', 13, true),
       ('Party', 14, true),
       ('Board Games', 15, true),
       ('Card', 16, true),
       ('Arcade', 17, true),
       ('Action', 18, true),
       ('Simulation', 19, true),
       ('Massively Multiplayer', 20, true),
       ('Casual', 21, true),
       ('Family', 22, true),
       ('Indie', 23, true),
       ('Multiplayer', 24, true);
